-- Supabase Database Schema Setup for Tailor Pro (Atelier)

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text unique not null,
    password text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable public read/write access (disable RLS for easy college demo setup, or configure rules)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read/write for demo" ON public.users 
    FOR ALL USING (true) WITH CHECK (true);

-- 2. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    order_id bigint generated by default as identity primary key,
    customer_name text not null,
    phone text not null,
    email text not null,
    dress_type text not null,
    chest double precision,
    waist double precision,
    shoulder double precision,
    sleeve double precision,
    height double precision,
    weight double precision,
    requirements text,
    order_status text default 'Measuring' not null,
    price double precision default 0.0 not null,
    order_date timestamp with time zone default timezone('utc'::text, now()) not null,
    estimated_date date
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read/write for demo" ON public.orders 
    FOR ALL USING (true) WITH CHECK (true);

-- 3. Feedback Table
CREATE TABLE IF NOT EXISTS public.feedback (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    category text not null,
    message text not null,
    submitted_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read/write for demo" ON public.feedback 
    FOR ALL USING (true) WITH CHECK (true);

-- Insert some sample orders for julian.stclair@heritage.com
INSERT INTO public.orders (customer_name, phone, email, dress_type, chest, waist, shoulder, sleeve, height, weight, requirements, order_status, price, estimated_date)
VALUES 
('Julian St. Clair', '+1 (212) 555-0198', 'julian.stclair@heritage.com', 'Bespoke Charcoal Wool Suit', 40.5, 34.0, 18.2, 34.5, 70.0, 160.0, 'Subtle herringbone pattern, modern slim-fit with wide peaked lapels.', 'Fitting', 3450.00, '2026-10-24'),
('Julian St. Clair', '+1 (212) 555-0198', 'julian.stclair@heritage.com', 'Signature White Poplin Shirt', 40.5, 34.0, 18.2, 34.5, 70.0, 160.0, 'Cream silk French cuff, stiff spread collar.', 'Measuring', 320.00, '2026-10-15');
